config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as rooms_views


app_name = "core"

urlpatterns = [path("", rooms_views.HomeView.as_view(), name="home")]
    

rooms/urls.py
from django.urls import path
from . import views as rooms_views

app_name = "rooms"

urlpatterns = [
    path("create/", rooms_views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", rooms_views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", rooms_views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", rooms_views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", rooms_views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/pothos/<int:photo_pk>/delete/",
        rooms_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        rooms_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", rooms_views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting", views.switch_hosting, name="switch-hosting"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center border-t py-10 font-medium text-gray-500">&copy; 2019 Airbnb, Inc. All
    rights reserved.</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute mx-auto left-0 right-0 flex justify-center top-0">
    {% for message in messages %}
    <li class="message font-medium bg-gray-700 z-10 rounded-full w-1/3 text-center text-white py-4 px-6 {% if message.tags %}{{ message.tags }}"
        {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-semibold h-full">

    {% if user.is_authenticated %}
    <li class="nav_link">
        <a href="{% url 'users:switch-hosting' %}">
            {% if request.session.is_hosting %}
            Stop hosting
            {% else %}
            Start hosting
            {% endif %}
        </a>
    </li>
    {% if request.session.is_hosting %}
    <li class="nav_link"><a href="{% url 'rooms:create' %}">Create Room</a></li>
    {% endif %}
    <li class="nav_link"><a href="{{user.get_absolute_url}}">Profile</a></li>
    <li class="nav_link"><a href="{% url 'users:logout' %}">Log Out</a></li>
    {% else %}
    <li class="nav_link"><a href="{% url 'users:login' %}">Log In</a></li>
    <li class="nav_link"><a href="{% url 'users:signup' %}">Sign Up</a></li>
    {% endif %}

</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn border-2 border-gray-700 mb-2 py-5 text-gray-700 font-medium">
        <i class="fab fa-github mr-2 fa-lg"></i>
        Continue with Github
    </a>

    <a href="{% url 'users:kakao-login' %}" class="btn border bg-yellow-400 mb-2 py-5 text-yellow-800 font-medium">
        <i class="fas fa-comment mr-2 fa-lg"></i>
        Continue with Kakao
    </a>
</div>
<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-500"></div>
    <span class="text-gray-700 font-semibold mx-2 text-sm">or</span>
    <div class="h-px w-full bg-gray-500"></div>
</div>