config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as rooms_views


app_name = "core"

urlpatterns = [path("", rooms_views.HomeView.as_view(), name="home")]
    

rooms/urls.py
from django.urls import path
from . import views as rooms_views

app_name = "rooms"

urlpatterns = [
    path("create/", rooms_views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", rooms_views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", rooms_views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", rooms_views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", rooms_views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/pothos/<int:photo_pk>/delete/",
        rooms_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        rooms_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", rooms_views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.utils import timezone
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse
from core import models as core_models
from .cal import Calendar


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Model Definition """

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):

    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Model definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", on_delete=models.CASCADE, related_name="photos")

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guest = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="rooms"
    )
    room_type = models.ForeignKey(
        "RoomType", on_delete=models.SET_NULL, null=True, related_name="rooms"
    )
    amenities = models.ManyToManyField("Amenity", blank=True, related_name="rooms")
    facilities = models.ManyToManyField("Facility", blank=True, related_name="rooms")
    house_rules = models.ManyToManyField("HouseRule", blank=True, related_name="rooms")

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)  # Call the real save() method

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    def total_rating(self):
        all_reviews = self.reviews.all()
        avg = 0.0

        if all_reviews:
            for review in all_reviews:
                avg += review.rating_average()
            avg /= all_reviews.count()
            avg = round(avg, 2)

        return avg

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]

            return photo.file.url
        except ValueError:
            return None

    def get_next_four(self):
        try:
            photos = self.photos.all()[1:5]
            return photos
        except ValueError:
            return None

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        if next_month == 13:
            next_month = 1
        next_year = this_year
        if next_month == 1:
            next_year += 1
        calendar = Calendar(this_year, this_month)
        next_calendar = Calendar(next_year, next_month)
        return [calendar, next_calendar]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guest",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "host",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins
from . import models, forms


class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    context_object_name = "rooms"


class RoomDetail(DetailView):

    """ RoomDetail Definition """

    model = models.Room


class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")

        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guest__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds_gte"] = beds

                if baths is not None:
                    filter_args["baths"] = baths

                if instant_book:
                    filter_args["instant_book"] = True

                if superhost:
                    filter_args["superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )
        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guest",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )
    template_name = "rooms/room_edit.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)

        if room.host.pk != self.request.user.pk:
            raise Http404()

        return room


class RoomPhotosView(mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)

        if room.host.pk != self.request.user.pk:
            raise Http404()

        return room


@login_required(login_url="users/login")
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can't delete this photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(mixins.LoggedInOnlyView, FormView):
    model = models.Photo
    template_name = "rooms/photo_create.html"
    fields = ("caption", "file")
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room Created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))


# from django.shortcuts import render, redirect
# from django.core.paginator import Paginator, EmptyPage
# from . import models as rooms_models


# def all_rooms(request):
#     _page = request.GET.get("page", 1)
#     room_list = rooms_models.Room.objects.all()
#     paginator = Paginator(room_list, 10)
#     try:
#         page = paginator.page(_page)
#         return render(request, "rooms/home.html", {"page": page})
#     except EmptyPage:
#         return redirect("/")


# def all_rooms(request):
#     page = request.GET.get("page", 1)
#     page = int(page or 1)
#     page_size = 10
#     limit = page * page_size
#     offset = limit - page_size
#     rooms = rooms_models.Room.objects.all()[offset:limit]
#     page_count = rooms_models.Room.objects.count() / page_size
#     page_count = ceil(page_count)

#     return render(
#         request,
#         "rooms/home.html",
#         {
#             "rooms": rooms,
#             "page": page,
#             "page_count": page_count,
#             "page_range": range(1, page_count + 1),
#         },
#     )


# import math
# from django.shortcuts import render
# from django.core.paginator import Paginator
# from . import models as rooms_models


# def all_rooms(request):
#     page = request.GET.get("page")
#     room_list = rooms_models.Room.objects.all()
#     paginator = Paginator(room_list, 10)
#     rooms = paginator.get_page(page)

#     return render(request, "rooms/home.html", {"page": rooms})

templates/rooms/detail.html
{% extends 'base.html' %}

{% block page_name %}
Home
{% endblock page_name %}

{% block content %}
<div>
    <p>{{ room.name }}</p>
    <p>{{ room.description }}</p>
    <p>{{ room.country }}</p>
    <p>{{ room.city }}</p>
    <p>{{ room.price }}</p>
    <p>{{ room.address }}</p>
    <p>{{ room.beds }}</p>
    <p>{{ room.bedrooms }}</p>
    <p>{{ room.baths }}</p>
    <p>{{ room.check_in }}</p>
    <p>{{ room.check_out }}</p>
    <p>{{ room.instant_book }}</p>
    <p>{{ room.host }}</p>
    <p>{{ room.room_type }}</p>
    <p>{{ room.amenities }}</p>
</div>
{% endblock %}

templates/rooms/photo_create.html
{% extends 'base.html' %}

{% block page_title %}
Upload Room
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'mixins/room/room_form.html' with form=form cta="Upload Photo" %}
</div>
{% endblock %}

templates/rooms/photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
Update photo
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'mixins/room/room_form.html' with form=form cta="Update photo" %}
</div>
{% endblock %}

templates/rooms/room_create.html
{% extends 'base.html' %}

{% block page_title %}
Create Room
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'mixins/room/room_form.html' with form=form cta="Create Room" %}
</div>
{% endblock %}

templates/rooms/room_detail.html
{% extends 'base.html' %}
{% load is_booked %}

{% block page_title %}
{{ room.name }}
{% endblock page_title %}

{% block content %}
<div class="container max-w-full h-75vh mb-20 flex mx-auto">
    <div style="background-image:url({{room.first_photo}})" class="w-1/2 h-full bg-cover bg-center"></div>
    <div class="w-1/2 flex flex-wrap">
        {% for photo in room.get_next_four %}
        <div style="background-image:url({{photo.file.url}})"
            class="w-1/2 h-auto bg-cover bg-center border border-gray-700"></div>
        {% endfor %}
    </div>
</div>

<div class="container mx-auto flex justify-around pb-56">
    <div class="w-1/2">
        <div class="flex justify-between">
            <div class="mr-10 mb-5">
                <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                <span class="font-light text-gray-700">{{room.city}}</span>
            </div>
            <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                {% include 'mixins/user_avatar.html' with user=room.host %}
                <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
            </a>
        </div>
        <div class="flex border-section">
            <span class="mr-5 font-light">{{room.room_type}}</span>
            <span class="mr-5 font-light">{{room.beds}} bed{{room.beds|pluralize}}</span>
            <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
            <span class="mr-5 font-light">{{room.baths}} bath{{room.baths|pluralize}}</span>
            <span class="mr-5 font-light">{{room.guest}} guest{{room.guest|pluralize}}</span>
        </div>
        <p class="border-section">{{room.description}}</p>

        {% if room.amenities.count > 0 %}
        <div class="border-section">
            <h4 class="text-xl font-medium mb-5">Amenities</h4>
            {% for a in room.amenities.all %}
            <li class="mb-2">{{a}}</li>
            {% endfor %}
        </div>
        {% endif %}

        {% if room.facilities.count > 0 %}
        <div class="border-section">
            <h4 class="text-xl font-medium mb-5">Fcilities</h4>
            {% for f in room.facilities.all %}
            <li class="mb-2">{{f}}</li>
            {% endfor %}
        </div>
        {% endif %}

        {% if room.house_rules.count > 0 %}
        <div class="border-section">
            <h4 class="text-xl font-medium mb-5">House Rules</h4>
            {% for r in room.house_rules.all %}
            <li class="mb-2">{{r}}</li>
            {% endfor %}
        </div>
        {% endif %}
        <div class="mt-10">
            <h4 class="text-2xl font-medium mb-5">Reviews</h4>
            <div class="flex items-center">
                <div>
                    <i class="fas fa-star text-teal-500"></i>
                    <span class="font-bold text-xl">{{room.total_rating}}</span>
                </div>
                <div class="h-5 w-px bg-gray-400 mx-5"></div>
                <div>
                    <span class="font-bold text-xl">{{room.reviews.count}} </span>
                    <span>review{{room.reviews.count|pluralize}}</span>
                </div>
            </div>
            <div class="mt-10">
                {% for review in room.reviews.all %}
                <div class="border-section">
                    <div class="flex mb-3">
                        <div class="mr-5">
                            {% include 'mixins/user_avatar.html' with user=review.user h_and_w='h-10 w-10' text='text-xl'%}
                        </div>
                        <div class="flex flex-col">
                            <span class="font-medium">{{review.user.first_name}}</span>
                            <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                        </div>
                    </div>
                    <p>{{review.review}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="w-1/3">
        {% if room.host == user %}
        <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Button</a>
        {% else %}
        {% if not request.session.is_hosting %}

        {% for calendar in room.get_calendars %}
        <div class="mb-10">
            <span class="mb-8, text-center font-semibold text-lg block">{{calendar.get_month}} /
                {{calendar.year}}</span>
            <div class="cal-grid mb-4 mt-5">
                {% for day in calendar.day_names %}
                <span class="font-medium">{{day}}</span>
                {% endfor %}
            </div>
            <div class="cal-grid">
                {% for day in calendar.get_days %}
                    {% is_booked room day as is_booked_bool %}
                    {% if day.number != 0 %}
                        {% if day.past %}
                        <span class="bg-gray-200 w-full text-center rounded text-white p-1">{{day}}</span>
                        {% elif is_booked_bool %}
                        <span class="bg-gray-200 w-full text-center rounded text-white p-1 line-through">{{day}}</span>
                        {% else %}
                        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}"
                            class="bg-gray-200 w-full text-center rounded text-gray-700 p-1 hover:bg-teal-400 hover:text-white hover:font-medium cursor-pointer">{{day}}
                        </a>
                        {% endif %}
                    {% else %}
                        <span></span>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        {% endif %}
        {% endif %}
    </div>
</div>

{% endblock %}

templates/rooms/room_edit.html
{% extends 'base.html' %}

{% block page_title %}
Update Room
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="lg:w-5/12 md:w-1/2 xl:w-1/4 container mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'mixins/room/room_form.html' with form=form cta="Update Room" %}
    <div class="flex">
        <a href="{% url 'rooms:photos' room.pk %}" class="font-medium text-teal-500">Edit Photos</a>
    </div>
</div>
{% endblock %}

templates/rooms/room_list.html
{% extends 'base.html' %}

{% block page_title %}
Home
{% endblock page_title %}

{% block content %}

<div class="container mx-auto pb-10">
    <div class="bg-gray-800 rounded-xl h-50vh mt-32 mb-24 bg-cover bg-center -mx-16"
        style="background-image:url(https://images.unsplash.com/photo-1536315238512-4c8cebdaaf93?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&)">
    </div>

    <div class="flex flex-wrap -mx-16">
        {% for room in rooms %}
        {% include 'mixins/room_card.html' with room=room %}
        {% endfor %}
    </div>
    <div class="flex justify-center items-center mt-10">
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500"><i
                class="fas fa-arrow-left fa-lg"></i></a>
        {% endif %}

        <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}" class="text-teal-500"><i class="fas fa-arrow-right fa-lg"></i></a>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/rooms/room_photos.html
{% extends 'base.html' %}

{% block page_title %}
{{room.name}}'s Photos
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="container mx-auto my-10 flex flex-col">
    <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link my-10 w-1/6">Upload Photo</a>
    {% for photo in room.photos.all %}
    <div class="mb-5 border border-gray-400 p-6 flex justify-between">
        <div class="flex items-start">
            <img src="{{photo.file.url}}" class="w-32 h-32">
            <span class="ml-5 text-xl">{{photo.caption}}</span>
        </div>
        <div class="flex flex-col w-1/5">
            <a href="{% url 'rooms:edit-photo' room.pk photo.pk %}" class="btn-link mb-5 bg-teal-500">Edit</a>
            <a href="{% url 'rooms:delete-photo' room.pk photo.pk %}" class="btn-link bg-red-600">Delete</a>
        </div>
    </div>
    {% endfor %}
    <div class="flex justify-center mt-5">
        <a href="{% url 'rooms:edit' room.pk %}" class="text-teal-500 font-semibold text-xl">Back to
            Room</a>
    </div>
</div>
{% endblock %}

templates/rooms/search.html
{% extends 'base.html' %}


{% block page_title %}
Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<h2>Search!</h2>

<form method="get" action="{% url 'rooms:search' %}">
    {{form.as_p}}
    <div>
        <button>Search</button>
    </div>
</form>

<h3>Results</h3>
{% for room in rooms %}
<h3>{{room.name}}</h3>
{% endfor %}

{% endblock %}