config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as rooms_views


app_name = "core"

urlpatterns = [path("", rooms_views.HomeView.as_view(), name="home")]
    

rooms/urls.py
from django.urls import path
from . import views as rooms_views

app_name = "rooms"

urlpatterns = [
    path("create/", rooms_views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", rooms_views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", rooms_views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", rooms_views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", rooms_views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/pothos/<int:photo_pk>/delete/",
        rooms_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        rooms_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", rooms_views.SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://kit.fontawesome.com/e7cfbd3221.js" crossorigin="anonymous"></script>
    <title>
        {% block page_title %}
        {% endblock page_title %} | Nbnb
    </title>
</head>

<body class="text-gray-800 mt-24 font-light">
    {% include 'partials/messages.html' %}
    <header
        class="container max-w-full flex items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white inset-0">
        <div class="flex w-1/3 items-center">
            <a class="pr-6" href="{% url 'core:home' %}">
                <img class="w-10 self-center" src="{% static 'img/logo.png' %}">
            </a>
            {% block search-bar %}
            <form class="w-full mb-0" method="get" action="{% url 'rooms:search' %}">
                <input
                    class="w-9/12 search-box border px-5 py-3 rounded-sm w-64 shadow-md hover:shadow-lg text-base font-medium placeholder-gray-600 focus:outline-none"
                    name="city" placeholder="Search by City">
            </form>
            {% endblock search-bar %}
        </div>
        {% include 'partials/nav.html' %}
    </header>
    {% block content %}
    {% endblock %}
    {% include 'partials/footer.html' %}
</body>

</html>