config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as rooms_views


app_name = "core"

urlpatterns = [path("", rooms_views.HomeView.as_view(), name="home")]
    

reservations/urls.py
from django.urls import path
from . import views


app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models


class BookedDay(core_models.TimeStampedModel):

    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.day)


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        choices=STATUS_CHOICES, max_length=9, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="reservations"
    )
    room = models.ForeignKey(
        "rooms.Room", on_delete=models.CASCADE, related_name="reservations"
    )

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finish = self.check_out < now

        if is_finish:
            BookedDay.objects.filter(reservation=self).delete()

        return is_finish

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            difference = end - start
            exisiting_booked_day = BookedDay.objects.filter(
                day__range=(start, end)
            ).exists()
            if not exisiting_booked_day:
                super().save(*args, **kwargs)
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        return super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from rooms import models as room_models
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


def create(request, room, year, month, day):

    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't Reserve That Room")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        
        form = review_forms.CreateReviewForm()
        return render(
            self.request,
            "reservations/detail.html",
            context={"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404

    if verb == "confirmed":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "canceled":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()

    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

templates/reservations/detail.html
{% extends 'base.html' %}

{% block page_title %}
Reservation {{reservation.check_in}}
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="container mx-auto my-10 flex flex-col">
    <div class="w-3/4 mx-auto">
        <div class="font-medium text-2xl text-gray-700 mb-3">Contact Your Host</div>
        <div class="w-full h-25vh bg-cover bg-center rounded-t"
            style="background-image:url({{reservation.room.first_photo}})">
        </div>
        <div class="border border-gray-300 p-5">
            <div class="font-normal text-gray-600">{{reservation.check_in}} ~ {{reservation.check_out}}
                <span
                    class="ml-4 {% if reservation.status == 'pending' %}text-yellow-500{%elif reservation.status == 'calceled' %}text-red-700{% else %}text-teal-600{% endif %}">
                    {{reservation.get_status_display}}
                </span>
            </div>
            <div class="text-xl font-medium text-gray-600 mt-1">{{reservation.room.name}}</div>
        </div>
        <div class="flex border border-gray-300 p-5 items-start px-8">
            <div class="flex flex-col justify-center pt-5">
                <div>
                    {% include 'mixins/user_avatar.html' with user=reservation.room.host%}
                </div>
                <div class="text-center mt-2">{{reservation.room.host.first_name}}</div>
            </div>
            <div class="ml-10">
                <div class="font-semibold text-gray-700 text-lg">Contact Your Airbnb Host</div>
                <div class="w-5/6 font-medium text-gray-600 mb-8">Your host is the best person to contact for questions
                    about
                    your reservation.</div>
                <a href="#" class="btn-link px-20 py-2">Send a Message</a>
            </div>
        </div>
        <div>
            {% if reservation.status != 'cancel' %}
                <div class="flex border border-gray-300 items-start py-10 px-5 justify-between">
                {% if reservation.status == 'confirmed' and reservation.is_finished %}
                    <div class="flex flex-col">
                    <span class="font-medium text-2xl text-center w-full mb-8">Write your review</span>
                    <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-2/4 mx-auto">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn-link mt-5">Submit Review</button>
                    </form>
                    </div>
                {% else %}
                        {% if reservation.status == 'pending' %}
                        <a href="{% url 'reservations:edit' reservation.pk 'canceled' %}" class="btn-link px-10 py-2 w-auto mx-20">Cancel Reservation</a>
                            {% if reservation.room.host != user %}
                                <a href="{% url 'reservations:edit' reservation.pk 'confirmed' %}" class="btn-link px-10 py-2 w-auto mx-20">Confirm Reservation</a>
                            {% endif %}
                        {% endif %}
                {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}